export const resources = [
  {
    key: 'colaboradores',
    label: 'Colaboradores',
    endpoint: 'api/colaboradores',
    listEndpoint: 'api/colaboradores/admin/all',
    idField: 'noColaborador',
    description: 'Gestiona los colaboradores activos y sus datos operativos.',
    uniqueFields: ['noColaborador', 'email', 'nfc_id'],
    fields: [
      { name: 'noColaborador', label: 'No. Colaborador', type: 'text', required: true },
      { name: 'nombre', label: 'Nombre', type: 'text', required: true },
      { name: 'apellidos', label: 'Apellidos', type: 'text', required: true },
      { name: 'area', label: 'Área', type: 'text', placeholder: 'OPERACION' },
      { name: 'puesto', label: 'Puesto', type: 'text', placeholder: 'OPERADOR / AUXILIAR' },
      { name: 'nivelUsuario', label: 'Nivel usuario', type: 'select', options: ['OPERADOR', 'SUPERVISOR', 'ADMIN'], required: true },
      { name: 'estacion', label: 'Estación', type: 'text', placeholder: 'MEXT1' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'telefono', label: 'Teléfono', type: 'text' },
      { name: 'status', label: 'Estatus', type: 'select', options: ['ACTIVO', 'INACTIVO'] },
      { name: 'nfc_id', label: 'NFC ID', type: 'text' },
      { name: 'fecha_ingreso', label: 'Fecha ingreso', type: 'date' },
      { name: 'tia', label: 'TIA', type: 'text' },
    ],
    columns: [
      { key: 'noColaborador', label: 'No.' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'apellidos', label: 'Apellidos' },
      { key: 'nivelUsuario', label: 'Nivel' },
      { key: 'estacion', label: 'Estación' },
      { key: 'status', label: 'Estatus' },
      { key: 'nfc_id', label: 'NFC' },
    ],
  },
  {
    key: 'operadores',
    label: 'Operadores',
    endpoint: 'api/operadores',
    idField: 'noColaborador',
    description: 'Catálogo de operadores disponibles para asignaciones.',
    uniqueFields: ['noColaborador', 'siglas'],
    fields: [
      { name: 'noColaborador', label: 'No. Colaborador', type: 'text', required: true },
      { name: 'nombre', label: 'Nombre', type: 'text', required: true },
      { name: 'apellidos', label: 'Apellidos', type: 'text', required: true },
      { name: 'siglas', label: 'Siglas', type: 'text', required: true },
      { name: 'fotoPerfil', label: 'Foto perfil (URL)', type: 'text', placeholder: '/images/colaborators/141.png' },
      { name: 'estacion', label: 'Estación', type: 'text' },
      { name: 'area', label: 'Área', type: 'text', placeholder: 'OPERACION' },
      { name: 'puesto', label: 'Puesto', type: 'text', placeholder: 'OPERADOR' },
      { name: 'sillaAsignada', label: 'Silla asignada', type: 'number', placeholder: '0 = sin silla' },
      { name: 'status', label: 'Estatus', type: 'select', options: ['ACTIVO', 'INACTIVO'] },
      { name: 'telefono', label: 'Teléfono', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'fecha_ingreso', label: 'Fecha ingreso', type: 'date' },
      { name: 'tia', label: 'TIA', type: 'text' },
    ],
    columns: [
      { key: 'noColaborador', label: 'No.' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'apellidos', label: 'Apellidos' },
      { key: 'siglas', label: 'Siglas' },
      { key: 'estacion', label: 'Estación' },
      { key: 'status', label: 'Estatus' },
      { key: 'sillaAsignada', label: 'Silla' },
    ],
  },
  {
    key: 'pulseras',
    label: 'Pulseras',
    endpoint: 'api/pulseras',
    idField: 'nfc_id',
    description: 'Control de pulseras NFC asignadas y disponibles.',
    uniqueFields: ['nfc_id'],
    fields: [
      { name: 'nfc_id', label: 'NFC ID', type: 'text', required: true },
      { name: 'id', label: 'ID interno', type: 'number' },
      { name: 'noColaborador', label: 'No. Colaborador', type: 'text' },
      { name: 'estacion', label: 'Estación', type: 'text' },
      { name: 'asignada', label: 'Asignada', type: 'select', options: ['0', '1'], placeholder: '1 = Sí, 0 = No' },
    ],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'nfc_id', label: 'NFC ID' },
      { key: 'noColaborador', label: 'Colaborador' },
      { key: 'estacion', label: 'Estación' },
      { key: 'asignada', label: 'Asignada' },
    ],
  },
  {
    key: 'vuelos',
    label: 'Vuelos',
    endpoint: 'api/vuelos',
    listEndpoint: 'api/vuelos/admin/all',
    idField: 'id_vuelo',
    description: 'Administración de vuelos y horarios publicados.',
    uniqueFields: ['id_vuelo', 'flight_number'],
    fields: [
      { name: 'id_vuelo', label: 'ID Vuelo', type: 'text', required: true },
      { name: 'flight_number', label: 'No. Vuelo', type: 'text', required: true },
      { name: 'latest_departure_airport', label: 'Origen', type: 'text' },
      { name: 'latest_arrival_airport', label: 'Destino', type: 'text' },
      { name: 'published_departure_time', label: 'Hora salida publicada', type: 'datetime-local' },
      { name: 'published_arrival_time', label: 'Hora llegada publicada', type: 'datetime-local' },
      { name: 'servicio_silla', label: 'Servicio silla', type: 'select', options: ['true', 'false'], placeholder: 'true/false' },
      { name: 'tipoServicio', label: 'Tipo Servicio', type: 'select', options: ['LLEGADAS', 'SALIDAS'], required: true },
      { name: 'tipoVuelo', label: 'Tipo Vuelo', type: 'select', options: ['INTERNACIONAL', 'NACIONAL'], required: true },
      { name: 'fechaInput', label: 'Fecha', type: 'date' },
      { name: 'estacion', label: 'Estación', type: 'text' },
      { name: 'status', label: 'Status', type: 'text', placeholder: '0 = programado' },
    ],
    columns: [
      { key: 'flight_number', label: 'Vuelo' },
      { key: 'latest_departure_airport', label: 'Origen' },
      { key: 'latest_arrival_airport', label: 'Destino' },
      { key: 'tipoServicio', label: 'Servicio' },
      { key: 'tipoVuelo', label: 'Tipo' },
      { key: 'estacion', label: 'Estación' },
      { key: 'status', label: 'Estatus' },
    ],
  },
  {
    key: 'vuelos-api',
    label: 'Vuelos API (Admin)',
    endpoint: 'api/vuelos/admin/vuelos-api',
    listEndpoint: 'api/vuelos/admin/vuelos-api/all',
    idField: '_id',
    description: 'Vista de solo lectura del feed completo de vuelos_api.',
    uniqueFields: ['_id'],
    readOnly: true,
    columns: [
      { key: 'flight_number', label: 'Vuelo' },
      { key: 'airline', label: 'Aerolínea' },
      { key: 'latest_departure_airport', label: 'Origen' },
      { key: 'latest_arrival_airport', label: 'Destino' },
      { key: 'published_departure_time', label: 'Salida publicada' },
      { key: 'published_arrival_time', label: 'Llegada publicada' },
      { key: 'status', label: 'Estatus' },
    ],
    fields: [],
  },
  {
    key: 'servicios-vuelo-admin',
    label: 'Servicios por Vuelo (Admin)',
    endpoint: 'api/vuelos/admin/servicios-vuelo',
    listEndpoint: 'api/vuelos/admin/servicios-vuelo/all',
    idField: '_id',
    description: 'Consulta global de servicios capturados por cada vuelo.',
    uniqueFields: ['_id'],
    readOnly: true,
    columns: [
      { key: 'idVuelo', label: 'ID Vuelo' },
      { key: 'noVuelo', label: 'No. Vuelo' },
      { key: 'fechaInput', label: 'Fecha' },
      { key: 'cantidadServicios', label: 'Servicios' },
      { key: 'asientos', label: 'Asientos' },
    ],
    fields: [],
  },
  {
    key: 'bitacora',
    label: 'Bitácora',
    endpoint: 'api/bitacora',
    idField: '_id',
    description: 'Registro de eventos y seguimiento en turnos.',
    uniqueFields: ['_id'],
    filters: [
      { name: 'estacion', label: 'Filtrar por estación', type: 'text', placeholder: 'MEXT1' },
      { name: 'fecha_registro', label: 'Rango de fechas', type: 'date-range' },
    ],
    fields: [
      { name: '_id', label: 'ID', type: 'text', required: true },
      { name: 'noColaborador', label: 'No. Colaborador', type: 'text', required: true },
      { name: 'fecha_registro', label: 'Fecha registro', type: 'date', required: true },
      { name: 'entrada', label: 'Hora entrada', type: 'datetime-local' },
      { name: 'salida', label: 'Hora salida', type: 'datetime-local' },
      { name: 'register_by', label: 'Registrado por', type: 'text' },
      { name: 'status', label: 'Estatus', type: 'text', placeholder: 'Turno Terminado' },
      { name: 'noFila', label: 'No. fila', type: 'number' },
      { name: 'estacion', label: 'Estación', type: 'text' },
      { name: 'ultimoServicio', label: 'Último servicio', type: 'text' },
      { name: 'noSilla', label: 'Silla asignada', type: 'text' },
    ],
    columns: [
      { key: '_id', label: 'ID' },
      { key: 'noColaborador', label: 'Colaborador' },
      { key: 'estacion', label: 'Estación' },
      { key: 'status', label: 'Estatus' },
      { key: 'fecha_registro', label: 'Fecha' },
      { key: 'entrada', label: 'Entrada' },
      { key: 'salida', label: 'Salida' },
      { key: 'noSilla', label: 'Silla' },
    ],
  },
  {
    key: 'servicios',
    label: 'Servicios',
    endpoint: 'api/servicios',
    idField: '_id',
    description: 'Servicios especiales asociados a vuelos y operadores.',
    uniqueFields: ['_id', 'pnr'],
    fields: [
      { name: '_id', label: 'ID', type: 'text', required: true },
      { name: 'nombrePax', label: 'Nombre pasajero', type: 'text' },
      { name: 'aerolinea', label: 'Aerolínea', type: 'text', required: true },
      { name: 'noVuelo', label: 'No. Vuelo', type: 'text', required: true },
      { name: 'noAsiento', label: 'No. Asiento', type: 'text', placeholder: 'S/A' },
      { name: 'origenVuelo', label: 'Origen', type: 'text' },
      { name: 'destinoVuelo', label: 'Destino', type: 'text' },
      { name: 'fechaInput', label: 'Fecha servicio', type: 'date', required: true },
      { name: 'horaInicio', label: 'Hora inicio', type: 'datetime-local' },
      { name: 'horaVuelo', label: 'Hora vuelo', type: 'datetime-local' },
      { name: 'estacion', label: 'Estación', type: 'text', required: true },
      { name: 'usuarioInicio', label: 'Usuario inicio', type: 'number' },
      { name: 'noColaborador', label: 'No. Colaborador', type: 'text' },
      { name: 'statusServicio', label: 'Estatus servicio', type: 'select', options: ['PENDIENTE', 'ASIGNADO', 'FINALIZADO'] },
      { name: 'tipoService', label: 'Tipo servicio (LL/SAL)', type: 'select', options: ['LLEGADAS', 'SALIDAS'] },
      { name: 'int_nac', label: 'Internacional/Nacional', type: 'select', options: ['INTERNACIONAL', 'NACIONAL'] },
      { name: 'pnr', label: 'PNR', type: 'text', required: true },
      { name: 'tipoSilla', label: 'Tipo de silla', type: 'select', options: ['WCHR', 'WCHS'] },
      { name: 'conexion', label: 'Conexión', type: 'text', placeholder: 'S/C' },
      { name: 'noMostrador', label: 'Mostrador', type: 'text' },
      { name: 'sala', label: 'Sala', type: 'text' },
      { name: 'uh', label: 'UH', type: 'text', placeholder: 'UH' },
    ],
    columns: [
      { key: '_id', label: 'ID' },
      { key: 'aerolinea', label: 'Aerolínea' },
      { key: 'noVuelo', label: 'No. Vuelo' },
      { key: 'tipoSilla', label: 'Tipo silla' },
      { key: 'statusServicio', label: 'Estatus' },
      { key: 'estacion', label: 'Estación' },
      { key: 'pnr', label: 'PNR' },
    ],
  },
  {
    key: 'support',
    label: 'Support',
    endpoint: 'api/support',
    idField: 'id',
    description: 'Tickets de soporte y seguimiento.',
    uniqueFields: ['id'],
    fields: [
      { name: 'id', label: 'ID', type: 'text', required: true },
      { name: 'titulo', label: 'Título', type: 'text', required: true },
      { name: 'categoria', label: 'Categoría', type: 'text' },
      { name: 'estatus', label: 'Estatus', type: 'select', options: ['ABIERTO', 'EN_PROCESO', 'CERRADO'] },
      { name: 'prioridad', label: 'Prioridad', type: 'select', options: ['BAJA', 'MEDIA', 'ALTA'] },
    ],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'titulo', label: 'Título' },
      { key: 'categoria', label: 'Categoría' },
      { key: 'estatus', label: 'Estatus' },
    ],
  },
  {
    key: 'amonestaciones',
    label: 'Amonestaciones',
    endpoint: 'api/amonestaciones',
    idField: '_id',
    description: 'Historial de amonestaciones aplicadas.',
    uniqueFields: ['_id'],
    fields: [
      { name: 'fechaInput', label: 'Fecha', type: 'date', required: true },
      { name: 'horaRegistro', label: 'Hora registro', type: 'datetime-local' },
      { name: 'noColaboradorRegistro', label: 'No. Colaborador (registra)', type: 'text', required: true },
      { name: 'noColaboradorAmonestado', label: 'No. Colaborador amonestado', type: 'text', required: true },
      { name: 'estacion', label: 'Estación', type: 'text' },
      { name: 'motivo', label: 'Motivo', type: 'textarea', required: true },
      {
        name: 'sancion',
        label: 'Sanción',
        type: 'select',
        options: ['VERBAL', 'ESCRITA', 'SUSPENSION'],
        required: true,
      },
    ],
    columns: [
      { key: 'fechaInput', label: 'Fecha' },
      { key: 'noColaboradorAmonestado', label: 'Amonestado' },
      { key: 'sancion', label: 'Sanción' },
      { key: 'estacion', label: 'Estación' },
      { key: 'motivo', label: 'Motivo' },
    ],
  },
  {
    key: 'pasajeros-vuelo',
    label: 'Pasajeros Vuelo',
    endpoint: 'api/pasajeros-vuelo',
    idField: 'id',
    description: 'Pasajeros asociados a un vuelo y servicios.',
    uniqueFields: ['id', 'pnr'],
    fields: [
      { name: 'id', label: 'ID', type: 'text', required: true },
      { name: 'nombrePax', label: 'Nombre pasajero', type: 'text', required: true },
      { name: 'noVuelo', label: 'No. Vuelo', type: 'text', required: true },
      { name: 'asiento', label: 'Asiento', type: 'text' },
      { name: 'estatus', label: 'Estatus', type: 'select', options: ['PENDIENTE', 'LISTO', 'ABORDADO'] },
    ],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'nombrePax', label: 'Pasajero' },
      { key: 'noVuelo', label: 'No. Vuelo' },
      { key: 'asiento', label: 'Asiento' },
    ],
  },
  {
    key: 'reportes',
    label: 'Reportes',
    endpoint: 'api/reportes',
    idField: 'id',
    description: 'Reportes operativos y administrativos.',
    uniqueFields: ['id'],
    fields: [
      { name: 'id', label: 'ID', type: 'text', required: true },
      { name: 'titulo', label: 'Título', type: 'text', required: true },
      { name: 'tipo', label: 'Tipo', type: 'text' },
      { name: 'estatus', label: 'Estatus', type: 'select', options: ['BORRADOR', 'PUBLICADO', 'CERRADO'] },
    ],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'titulo', label: 'Título' },
      { key: 'tipo', label: 'Tipo' },
      { key: 'estatus', label: 'Estatus' },
    ],
  },
];

export const resourceMap = resources.reduce((acc, resource) => {
  acc[resource.key] = resource;
  return acc;
}, {});
